#!/usr/bin/env bash
# Displays 'to infinity and beyond' indefinitely with 'sleep 2' in btw each iteration   
# 'I am invincible!!!' when receiving a SIGTERM signal

# Set up the trap outside the loop
trap 'echo "I am invincible!!!"; exit' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
e
